### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by AngelliaX** [hhhxiao/hhhxiao.github.io#1]
Hello man, do you still remember me? we met in a qq group chat and talked about the Trapdoor plugin for Minecraft Bedrock, also I asked you some technical issue to finish this plugin idk if you can still remember it https://angelliax.github.io/2021/10/29/lag-chunk-detection-algorithm/

I had your website in my friend page https://angelliax.github.io/links/, so sometimes I do go to your website for fun

Do you want to add my website to your friend chains? idk it's up to you, cuz I don't really active in the Chinese community at all so we can't barely chat to each other lol

Also good luck on the journey after your graduation

**Comment by hhhxiao** [comment]
I will

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/hhhxiao.github.io/commit/a38a7e99b64465244ff03d0042f7cb42c0d8438b
